apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes-ninix
spec:
  replicas : 15
  selector:
    matchLabels:
      app: mon-ninix
  template:
    metadata:
      labels:
        app: mon-ninix 
      annotations:
        kubernetes.io/change-cause: "version 1"
    spec:
      containers:
      - name: mon-ctn-ninix
        image: cheliel/site-args-v.2:latest
        ports:
        - containerPort: 80
