apiVersion: apps/v1
kind: Deployment
metadata:
  name: mes-caddies
spec:
  replicas : 3
  selector:
    matchLabels:
      app: app-caddy
  template:
    metadata:
      labels:
        app: app-caddy 
      annotations:
        kubernetes.io/change-cause: "version 1"
    spec:
      containers:
      - name: caddy-ctn
        image: caddy:latest
        ports:
        - containerPort: 80
