version: '3'
services:
  convertion-front:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3082:5000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - ms-cci

networks:
  ms-cci:
    external: true
