apiVersion: v1
kind: Pod
metadata: 
  name: ninix
  labels:
    app: monsite
spec: 
  containers: 
  - name: cont-ninix
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pv-volume
      mountPath: /usr/share/nginx/html
  volumes: 
  - name: pv-volume
    configMap:
      name: my-pvc-stick 