apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-stick
spec:
  storageClassName: ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
#  selector:
#    matchLabels:
#      disk: ssd