apiVersion: v1
kind: Pod
metadata: 
  name: pod-papache
  labels:
    app: app-apache
spec: 
  containers: 
  - name: cont-papache
    image: httpd:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80 