apiVersion: v1
kind: Service
metadata:
  name: svc-apache-nodeport
spec:
  type: NodePort
  selector:
    app: app-apache
  ports:
    # PORT =>  Port sur lequel le service écoute
    # TARGET PORT => Port sur lequel les pods répondent
    - nodePort: 31000
      port: 8080
      targetPort: 80
